revision = "main"

[data]
path = "data/french_rap_lyrics"

[dataset_encoding]
context_length = 512
encoding = "r50k_base"

[training]
batch_size = 24

[wandb]    
mode = "online"  # offline or online or disabled
