revision = "main"

[data]
path = "data/french_rap_lyrics"

[corpus]
encoding = "r50k_base"

[model]
context_length = 1024
num_heads = 6
num_layers = 15
hidden_dim = 512

[training]
seed = 42
lr = 1e-3
batch_size = 18

[evaluation]
sample_text = "Les vrais savent que "
new_tokens = 50
artist_token = 1

[wandb]    
mode = "disabled"  # offline or online or disabled
