revision = "main"

[data]
path = "data/french_rap_lyrics"

[corpus]
encoding = "r50k_base"
split_train_val = 0.85

[model]
context_length = 256
num_heads = 8
num_layers = 18
hidden_dim = 424

[training]
num_training_steps = 20000
seed = 42
lr = 1e-3
batch_size = 64

[scheduler]
gamma = 0.925

[evaluation]
sample_text = "Les vrais savent que "
new_tokens = 50
artist_token = 1

[wandb]    
mode = "online"  # offline or online or disabled
group = "fullrun"
tags = []
